import Cocoa

// Only links generated by the conversation UI can mutate its messages.
private let followUpActionAttribute = NSAttributedString.Key("langminFollowUpAction")
private let followUpBlockAttribute = NSAttributedString.Key("langminFollowUpBlock")

// Animate the typing dots with Core Animation, without timers or text replacement.
final class ResultFollowUpActivityView: NSView {
    static let size = NSSize(width: 48, height: 22)
    private let dots = (0..<3).map { _ in CALayer() }

    // init(): Create the follow-up activity dots and observe
    // motion-accessibility changes.
    init() {
        super.init(frame: NSRect(origin: .zero, size: Self.size))
        wantsLayer = true
        layer?.cornerRadius = 9
        // Lay out the activity dots at evenly spaced positions.
        for (index, dot) in dots.enumerated() {
            dot.frame = NSRect(x: 12.5 + Double(index) * 9, y: 8.5, width: 5, height: 5)
            dot.cornerRadius = 2.5
            dot.opacity = 0.45
            layer?.addSublayer(dot)
        }
        setAccessibilityElement(true)
        setAccessibilityRole(.progressIndicator)
        setAccessibilityLabel(localized("followup_working", "Replying…"))
        updateColors()
        NSWorkspace.shared.notificationCenter.addObserver(self,
            selector: #selector(accessibilityOptionsChanged(_:)),
            name: NSWorkspace.accessibilityDisplayOptionsDidChangeNotification, object: nil)
    }

    // init?(coder): The activity view is built in code with its dot layers.
    required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }
    // deinit(): Remove workspace notifications before the activity view is
    // released.
    deinit { NSWorkspace.shared.notificationCenter.removeObserver(self) }

    // viewDidMoveToWindow(): Update activity animation when the view enters or
    // leaves a window.
    override func viewDidMoveToWindow() {
        super.viewDidMoveToWindow()
        updateAnimation()
    }

    // viewDidChangeEffectiveAppearance(): Refresh activity colors after an
    // appearance change.
    override func viewDidChangeEffectiveAppearance() {
        super.viewDidChangeEffectiveAppearance()
        updateColors()
    }

    // updateColors(): Resolve the activity background and dot colors in the
    // current appearance.
    private func updateColors() {
        effectiveAppearance.performAsCurrentDrawingAppearance {
            layer?.backgroundColor = NSColor.controlAccentColor.withAlphaComponent(0.08).cgColor
            // Resolve every dot against the same accent color.
            for dot in dots { dot.backgroundColor = NSColor.controlAccentColor.cgColor }
        }
    }

    // accessibilityOptionsChanged(notification): Apply changed motion
    // preferences to the activity animation.
    @objc private func accessibilityOptionsChanged(_ notification: Notification) { updateAnimation() }

    // updateAnimation([reduceMotion]): Preserve animation timing during layout.
    // Stop when detached or Reduce Motion is enabled.
    func updateAnimation(reduceMotion: Bool = NSWorkspace.shared.accessibilityDisplayShouldReduceMotion) {
        // Apply animation state independently to each staggered dot.
        for (index, dot) in dots.enumerated() {
            // Stop animation when detached or when the user requests reduced motion.
            guard window != nil, !reduceMotion else {
                dot.removeAnimation(forKey: "typing")
                continue
            }
            // Preserve an existing animation's timing across repeated layout updates.
            guard dot.animation(forKey: "typing") == nil else { continue }
            let lift = CAKeyframeAnimation(keyPath: "transform.translation.y")
            lift.values = [0, 1.5, 0, 0]
            let glow = CAKeyframeAnimation(keyPath: "opacity")
            glow.values = [0.45, 1, 0.45, 0.45]
            // Use matching timing for the vertical movement and opacity animations.
            for animation in [lift, glow] {
                animation.keyTimes = [0, 0.3, 0.6, 1]
                animation.duration = 1.25
                animation.timingFunctions = (0..<3).map { _ in CAMediaTimingFunction(name: .easeInEaseOut) }
            }
            let wave = CAAnimationGroup()
            wave.animations = [lift, glow]
            wave.duration = 1.25
            wave.beginTime = dot.convertTime(CACurrentMediaTime(), from: nil) + Double(index) * 0.16
            wave.repeatCount = .infinity
            wave.fillMode = .backwards
            dot.add(wave, forKey: "typing")
        }
    }
}

// Reserve space with a blank TextKit 1 attachment; the view draws the animation and provides
// accessibility.
final class ResultFollowUpActivityCell: NSTextAttachmentCell {
    // cellSize(): Reserve the activity view's footprint in the surrounding text
    // layout.
    override func cellSize() -> NSSize { ResultFollowUpActivityView.size }
    // draw(cellFrame, controlView): Leave drawing to the positioned activity
    // view; this attachment only reserves space.
    override func draw(withFrame cellFrame: NSRect, in controlView: NSView?) {}
}

// Keep follow-up activity and per-message hover actions aligned with conversation text.
class ResultConversationTextView: NSTextView {
    private(set) var followUpActivity: ResultFollowUpActivityView?
    private var positioningFollowUpActivity = false
    private var followUpTrackingArea: NSTrackingArea?
    private var followUpScrollObserver: NSObjectProtocol?
    private var hoveredFollowUpBlock: String?
    private var showingAccessibleActions = false
    private var updatingFollowUpActions = false

    // deinit(): Remove the scroll observer before releasing the conversation
    // view.
    deinit {
        // Remove a retained scroll observation when the conversation view is released.
        if let followUpScrollObserver { NotificationCenter.default.removeObserver(followUpScrollObserver) }
    }

    var followUpMouseLocation: NSPoint? {
        // Show pointer-dependent actions only in the key result window.
        guard let window, window.isKeyWindow else { return nil }
        return convert(window.convertPoint(fromScreen: NSEvent.mouseLocation), from: nil)
    }

    // updateTrackingAreas(): Track pointer movement within the visible
    // conversation area.
    override func updateTrackingAreas() {
        super.updateTrackingAreas()
        // Replace the old tracking region before creating one for current visible bounds.
        if let followUpTrackingArea { removeTrackingArea(followUpTrackingArea) }
        let area = NSTrackingArea(rect: .zero,
            options: [.mouseMoved, .mouseEnteredAndExited, .activeInKeyWindow, .inVisibleRect], owner: self, userInfo: nil)
        addTrackingArea(area)
        followUpTrackingArea = area
        updateFollowUpActionHover(at: followUpMouseLocation)
    }

    // viewDidMoveToSuperview(): Move scroll observation to the new enclosing
    // scroll view when the conversation changes hosts.
    override func viewDidMoveToSuperview() {
        super.viewDidMoveToSuperview()
        // Remove observation of the old scroll host before attaching to a new one.
        if let followUpScrollObserver { NotificationCenter.default.removeObserver(followUpScrollObserver) }
        followUpScrollObserver = nil
        // Scrolling changes the block beneath a stationary pointer too.
        if let clip = enclosingScrollView?.contentView {
            clip.postsBoundsChangedNotifications = true
            followUpScrollObserver = NotificationCenter.default.addObserver(
                forName: NSView.boundsDidChangeNotification, object: clip, queue: .main
            ) { [weak self] _ in
                // Ignore a delayed scroll notification after the conversation view is released.
                guard let self else { return }
                self.updateFollowUpActionHover(at: self.followUpMouseLocation)
            }
        }
    }

    // mouseMoved(event): Refresh per-message action hover as the pointer moves
    // through the conversation.
    override func mouseMoved(with event: NSEvent) {
        updateFollowUpActionHover(at: convert(event.locationInWindow, from: nil))
        super.mouseMoved(with: event)
    }

    // mouseEntered(event): Refresh per-message actions when the pointer enters
    // the conversation.
    override func mouseEntered(with event: NSEvent) {
        updateFollowUpActionHover(at: convert(event.locationInWindow, from: nil))
        super.mouseEntered(with: event)
    }

    // mouseExited(event): Clear message hover actions when the pointer leaves
    // the conversation.
    override func mouseExited(with event: NSEvent) {
        updateFollowUpActionHover(at: nil)
        super.mouseExited(with: event)
    }

    // followUpBlock(point): Treat the full message width and height as the
    // hover target, including space beside short lines.
    private func followUpBlock(at point: NSPoint) -> String? {
        // Require visible, nonempty laid-out text before locating a hovered message.
        guard visibleRect.contains(point), let storage = textStorage, storage.length > 0,
              let layoutManager, let textContainer else { return nil }
        layoutManager.ensureLayout(for: textContainer)
        let origin = textContainerOrigin
        let local = NSPoint(x: point.x - origin.x, y: point.y - origin.y)
        // Reject points outside the text container before finding a conversation block.
        guard local.x >= 0, local.x <= textContainer.containerSize.width, local.y >= 0 else { return nil }
        // Find the line from its leading edge; a lookup beside short text can select the next separator.
        let linePoint = NSPoint(x: textContainer.lineFragmentPadding + 1, y: local.y)
        let glyph = layoutManager.glyphIndex(for: linePoint, in: textContainer)
        // Do not inspect a character beyond the layout manager's glyph range.
        guard glyph < layoutManager.numberOfGlyphs else { return nil }
        let index = layoutManager.characterIndexForGlyph(at: glyph)
        var range = NSRange()
        // Require a valid character carrying conversation-block metadata.
        guard index < storage.length,
              let block = storage.attribute(followUpBlockAttribute, at: index, longestEffectiveRange: &range,
                                            in: NSRange(location: 0, length: storage.length)) as? String else { return nil }
        let glyphs = layoutManager.glyphRange(forCharacterRange: range, actualCharacterRange: nil)
        let rect = layoutManager.boundingRect(forGlyphRange: glyphs, in: textContainer)
        return local.y >= rect.minY && local.y <= rect.maxY ? block : nil
    }

    // updateFollowUpActionHover(point, [force = false], [showAll]): Change only
    // colors to preserve layout and selection. Keep actions visible for
    // VoiceOver.
    func updateFollowUpActionHover(at point: NSPoint?, force: Bool = false,
                                   showAll: Bool = NSWorkspace.shared.isVoiceOverEnabled) {
        // Avoid recursive hover updates and wait for text storage to exist.
        guard !updatingFollowUpActions, let storage = textStorage else { return }
        updatingFollowUpActions = true
        // Release the hover-action layout guard on every exit path.
        defer { updatingFollowUpActions = false }
        let block = point.flatMap { followUpBlock(at: $0) }
        // Skip attribute updates when neither hovered message nor accessibility visibility changed.
        guard force || block != hoveredFollowUpBlock || showAll != showingAccessibleActions else { return }
        hoveredFollowUpBlock = block
        showingAccessibleActions = showAll
        var changes: [(NSRange, NSColor)] = []
        storage.enumerateAttribute(followUpActionAttribute, in: NSRange(location: 0, length: storage.length)) { value, range, _ in
            // Ignore runs without a follow-up action marker.
            guard value != nil else { return }
            let actionBlock = storage.attribute(followUpBlockAttribute, at: range.location, effectiveRange: nil) as? String
            let visible = showAll || (block != nil && actionBlock == block)
            let color: NSColor = visible ? .linkColor : .clear
            // Collect only action runs whose visibility color actually changed.
            if (storage.attribute(.foregroundColor, at: range.location, effectiveRange: nil) as? NSColor) != color {
                changes.append((range, color))
            }
        }
        // Avoid a text-storage edit cycle when no colors need updating.
        guard !changes.isEmpty else { return }
        storage.beginEditing()
        // Apply the collected action-visibility changes in one text-storage transaction.
        for (range, color) in changes { storage.addAttribute(.foregroundColor, value: color, range: range) }
        storage.endEditing()
    }

    // layout(): Reposition the activity indicator after the conversation text
    // is laid out.
    override func layout() {
        super.layout()
        updateFollowUpActivity()
    }

    // updateFollowUpActivity(): Position the waiting bubble at its attachment
    // glyph as the text wraps or moves between views.
    func updateFollowUpActivity() {
        // Refresh after text replacement or resizing, even if the hovered message ID is unchanged.
        updateFollowUpActionHover(at: followUpMouseLocation, force: true)
        // Avoid recursive layout while positioning the activity view.
        guard !positioningFollowUpActivity else { return }
        // Show activity only when the final attachment represents an active follow-up placeholder.
        guard let storage = textStorage, storage.length > 0,
              let attachment = storage.attribute(.attachment, at: storage.length - 1, effectiveRange: nil) as? NSTextAttachment,
              attachment.attachmentCell is ResultFollowUpActivityCell,
              let layoutManager, let textContainer else {
            followUpActivity?.removeFromSuperview()
            followUpActivity = nil
            return
        }
        positioningFollowUpActivity = true
        // Allow subsequent activity layouts after this positioning pass finishes.
        defer { positioningFollowUpActivity = false }
        layoutManager.ensureLayout(for: textContainer)
        let glyphs = layoutManager.glyphRange(forCharacterRange: NSRange(location: storage.length - 1, length: 1), actualCharacterRange: nil)
        let rect = layoutManager.boundingRect(forGlyphRange: glyphs, in: textContainer)
            .offsetBy(dx: textContainerOrigin.x, dy: textContainerOrigin.y)
        let activity = followUpActivity ?? ResultFollowUpActivityView()
        // Attach the activity view once instead of adding it during every layout pass.
        if activity.superview !== self { addSubview(activity) }
        followUpActivity = activity
        activity.frame = NSRect(origin: rect.origin, size: ResultFollowUpActivityView.size)
    }
}

// Return sends and Shift-Return adds a line. Leave Return to the input method during composition.
final class ResultFollowUpInput: NSTextView {
    var onSubmit: (() -> Void)?
    // keyDown(event): Submit on Return unless Shift or an active input-method
    // composition requires normal text handling.
    override func keyDown(with event: NSEvent) {
        // Submit on Return or Enter while allowing Shift-newlines and input-method composition.
        if [36, 76].contains(event.keyCode), !event.modifierFlags.contains(.shift), !hasMarkedText() {
            onSubmit?()
        } else {
            // Let AppKit handle ordinary typing and composition keystrokes.
            super.keyDown(with: event)
        }
    }
}

// Make the follow-up model selector usable through keyboard focus and activation.
final class ResultFollowUpModelButton: NSButton {
    override var acceptsFirstResponder: Bool { true }
    // keyDown(event): Open model choices with Return, Enter, or Space; defer
    // other keys to AppKit.
    override func keyDown(with event: NSEvent) {
        // Activate the model button with the standard keyboard activation keys.
        if [36, 76, 49].contains(event.keyCode) { performClick(nil) }
        // Defer unrelated keys to normal button behavior.
        else { super.keyDown(with: event) }
    }
}

// Draw the action at full contrast even when AppKit disables an empty draft.
// NSButton still supplies keyboard, accessibility and disabled-click behavior.
final class ResultFollowUpSendButton: NSButton {
    var isBusy = false { didSet { needsDisplay = true } }

    private var circleRect: NSRect { bounds.insetBy(dx: 2.5, dy: 2.5) }

    // drawFocusRingMask(): Match the follow-up send button's focus ring to its
    // circular visual bounds.
    override func drawFocusRingMask() { NSBezierPath(ovalIn: circleRect).fill() }

    // draw(dirtyRect): Draw the blue send control with pressed feedback and its
    // current action symbol.
    override func draw(_ dirtyRect: NSRect) {
        let circle = NSBezierPath(ovalIn: circleRect)
        NSColor.systemBlue.setFill()
        circle.fill()
        // Darken an enabled send control while it is pressed.
        if isEnabled && cell?.isHighlighted == true {
            NSColor.black.withAlphaComponent(0.18).setFill()
            circle.fill()
        }
        NSColor.white.setFill()
        NSColor.white.setStroke()
        let center = NSPoint(x: bounds.midX, y: bounds.midY)
        // Show a stop square while a follow-up request is running.
        if isBusy {
            NSBezierPath(roundedRect: NSRect(x: center.x - 4, y: center.y - 4, width: 8, height: 8),
                         xRadius: 1.5, yRadius: 1.5).fill()
        } else {
            // Show a send arrow while the composer is idle.
            let top = center.y + (isFlipped ? -6 : 6)
            let bottom = center.y + (isFlipped ? 6 : -6)
            let arrow = NSBezierPath()
            arrow.lineWidth = 2
            arrow.lineCapStyle = .round
            arrow.lineJoinStyle = .round
            arrow.move(to: NSPoint(x: center.x, y: bottom))
            arrow.line(to: NSPoint(x: center.x, y: top))
            arrow.move(to: NSPoint(x: center.x - 4.5, y: center.y))
            arrow.line(to: NSPoint(x: center.x, y: top))
            arrow.line(to: NSPoint(x: center.x + 4.5, y: center.y))
            arrow.stroke()
        }
    }
}

// Present a follow-up draft, model selection, submission controls, and request errors together.
final class ResultFollowUpComposer: NSView, NSTextViewDelegate {
    let input = ResultFollowUpInput(frame: .zero)
    let modelButton = ResultFollowUpModelButton()
    private let placeholder = NSTextField(labelWithString: localized("followup_placeholder", "Ask a follow-up or request changes…"))
    private let status = NSTextField(labelWithString: "")
    private let send = ResultFollowUpSendButton()
    private let spinner = NSProgressIndicator()
    private var composerHeight: NSLayoutConstraint!
    private var errorHeight: NSLayoutConstraint!
    private var modelBottom: NSLayoutConstraint!
    var onSubmit: (() -> Void)?
    var onChange: ((String) -> Void)?
    var onChooseModel: ((NSView) -> Void)?
    var busy = false

    // init(): Build the follow-up editor and its controls beneath a separator
    // from the result.
    init() {
        super.init(frame: .zero)
        translatesAutoresizingMaskIntoConstraints = false
        let divider = NativeSeparator()
        divider.boxType = .separator
        divider.translatesAutoresizingMaskIntoConstraints = false
        addSubview(divider)
        let scroll = NSScrollView()
        scroll.drawsBackground = false
        scroll.hasVerticalScroller = true
        scroll.translatesAutoresizingMaskIntoConstraints = false
        input.isRichText = false
        input.isAutomaticQuoteSubstitutionEnabled = false
        input.isAutomaticDashSubstitutionEnabled = false
        input.font = .systemFont(ofSize: 13)
        input.textColor = .labelColor
        input.drawsBackground = false
        input.textContainerInset = NSSize(width: 0, height: 6)
        input.textContainer?.lineFragmentPadding = 0
        input.textContainer?.widthTracksTextView = true
        input.isHorizontallyResizable = false
        input.isVerticallyResizable = true
        input.autoresizingMask = [.width]
        input.delegate = self
        input.setAccessibilityLabel(localized("followup_title", "Follow-up"))
        // A second Return while sending must not cancel an in-flight reply.
        input.onSubmit = { [weak self] in
            // Submit only while the composer still exists and is not busy.
            guard let self, !self.busy else { return }
            self.onSubmit?()
        }
        scroll.documentView = input
        addSubview(scroll)
        // Overlay the empty-input hint and keep the send action keyboard
        // accessible.
        placeholder.font = .systemFont(ofSize: 13)
        placeholder.textColor = .placeholderTextColor
        placeholder.lineBreakMode = .byTruncatingTail
        placeholder.translatesAutoresizingMaskIntoConstraints = false
        addSubview(placeholder)
        send.isBordered = false
        send.focusRingType = .default
        send.target = self
        send.action = #selector(submit)
        send.translatesAutoresizingMaskIntoConstraints = false
        addSubview(send)
        // Reserve a separate status label for progress and errors.
        status.font = .systemFont(ofSize: 11)
        status.textColor = .secondaryLabelColor
        status.lineBreakMode = .byTruncatingTail
        status.translatesAutoresizingMaskIntoConstraints = false
        addSubview(status)
        // Expose model selection as a popup with room for a long model name.
        modelButton.isBordered = false
        modelButton.imagePosition = .imageTrailing
        modelButton.image = NSImage(systemSymbolName: "chevron.down", accessibilityDescription: nil)?
            .withSymbolConfiguration(NSImage.SymbolConfiguration(pointSize: 8, weight: .medium))
        modelButton.contentTintColor = .secondaryLabelColor
        modelButton.cell?.lineBreakMode = .byTruncatingTail
        modelButton.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
        modelButton.target = self
        modelButton.action = #selector(chooseModel)
        modelButton.setAccessibilityRole(.popUpButton)
        modelButton.translatesAutoresizingMaskIntoConstraints = false
        addSubview(modelButton)
        // Keep request activity beside the model selector.
        spinner.style = .spinning
        spinner.controlSize = .small
        spinner.isDisplayedWhenStopped = false
        spinner.translatesAutoresizingMaskIntoConstraints = false
        addSubview(spinner)
        // Collapse the error row until there is a message to show.
        composerHeight = heightAnchor.constraint(equalToConstant: 96)
        errorHeight = status.heightAnchor.constraint(equalToConstant: 0)
        modelBottom = modelButton.bottomAnchor.constraint(equalTo: status.topAnchor)
        NSLayoutConstraint.activate([
            composerHeight, errorHeight, modelBottom,
            divider.topAnchor.constraint(equalTo: topAnchor),
            divider.leadingAnchor.constraint(equalTo: leadingAnchor), divider.trailingAnchor.constraint(equalTo: trailingAnchor),
            scroll.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 22),
            scroll.topAnchor.constraint(equalTo: topAnchor, constant: 10),
            scroll.trailingAnchor.constraint(equalTo: send.leadingAnchor, constant: -10),
            scroll.heightAnchor.constraint(equalToConstant: 48),
            placeholder.leadingAnchor.constraint(equalTo: scroll.leadingAnchor),
            placeholder.topAnchor.constraint(equalTo: scroll.topAnchor, constant: 6),
            placeholder.trailingAnchor.constraint(lessThanOrEqualTo: scroll.trailingAnchor, constant: -8),
            send.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -18),
            send.centerYAnchor.constraint(equalTo: scroll.centerYAnchor),
            send.widthAnchor.constraint(equalToConstant: 30), send.heightAnchor.constraint(equalToConstant: 30),
            status.leadingAnchor.constraint(equalTo: scroll.leadingAnchor),
            status.bottomAnchor.constraint(equalTo: bottomAnchor, constant: -14),
            status.trailingAnchor.constraint(equalTo: send.trailingAnchor),
            modelButton.leadingAnchor.constraint(equalTo: scroll.leadingAnchor),
            modelButton.trailingAnchor.constraint(lessThanOrEqualTo: spinner.leadingAnchor, constant: -8),
            modelButton.heightAnchor.constraint(equalToConstant: 22),
            spinner.trailingAnchor.constraint(equalTo: send.trailingAnchor),
            spinner.centerYAnchor.constraint(equalTo: modelButton.centerYAnchor),
            spinner.widthAnchor.constraint(equalToConstant: 14), spinner.heightAnchor.constraint(equalToConstant: 14)
        ])
    }

    // init?(coder): The composer is built in code with its text editor and
    // action controls.
    required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }

    // hitTest(point): Clicking the placeholder should focus the editor
    // underneath it.
    override func hitTest(_ point: NSPoint) -> NSView? {
        let hit = super.hitTest(point)
        return hit === placeholder ? input : hit
    }

    // submit(): Forward submission to the result session that owns the
    // conversation.
    @objc private func submit() { onSubmit?() }
    // chooseModel(): Open the model picker only while no follow-up request is
    // running.
    @objc private func chooseModel() {
        // Prevent changing models during an active request.
        guard !busy else { return }
        onChooseModel?(modelButton)
    }

    // textDidChange(notification): Refresh the placeholder and submit state and
    // report draft changes to the owning session.
    func textDidChange(_ notification: Notification) {
        placeholder.isHidden = !input.string.isEmpty
        send.isEnabled = busy || !input.string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        onChange?(input.string)
    }

    // update(draft, busy, model, error): Synchronize the composer with the
    // saved draft, request state, model label, and error.
    func update(draft: String, busy: Bool, model: String, error: String?) {
        self.busy = busy
        // Replace editor text only when its visible value differs from the stored draft.
        if input.string != draft { input.string = draft }
        input.isEditable = !busy
        placeholder.isHidden = !draft.isEmpty
        let action = busy ? localized("cancel", "Cancel") : localized("followup_send", "Send follow-up")
        send.isBusy = busy
        send.setAccessibilityLabel(action)
        send.isEnabled = busy || !draft.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        let title = "\(busy ? localized("followup_working", "Replying…") : localized("followup_title", "Follow-up")) · \(model)"
        modelButton.attributedTitle = NSAttributedString(string: title, attributes: [
            .font: NSFont.systemFont(ofSize: 11), .foregroundColor: NSColor.secondaryLabelColor
        ])
        modelButton.setAccessibilityLabel(title)
        modelButton.isEnabled = !busy
        // Keep the model picker available after errors so the user can try another provider.
        status.stringValue = error ?? ""
        status.isHidden = error == nil
        status.textColor = .systemRed
        status.toolTip = error
        composerHeight.constant = error == nil ? 96 : 114
        errorHeight.constant = error == nil ? 0 : 14
        modelBottom.constant = error == nil ? 0 : 4
        busy ? spinner.startAnimation(nil) : spinner.stopAnimation(nil)
    }
}

// Coordinate follow-up model choices, request lifecycle, and conversation rendering for a result.
extension ViewerSession {
    // followUpModel(): Keep each conversation's model choice separate and
    // retain the active request's model during changes.
    func followUpModel() -> (id: String, name: String) {
        // Keep the running request's model label stable until that request finishes.
        if let model = followUpRequestModel { return model }
        let preferences = loadAppPreferences()
        let options = enabledExplanationModelOptions(preferences)
        let selected = options.first { $0.id == followUpSelectedModelID }
            ?? options.first { $0.id == config.conversation?.modelID }
            ?? options.first { $0.displayValue == config.textModel }
        let id = selected?.id ?? defaultEnabledExplanationModel(preferences)
        return (id, preferenceDisplayValue(for: id, options: options))
    }

    // selectFollowUpModel(id): Accept an enabled model choice only when the
    // session is alive and no request is running.
    func selectFollowUpModel(_ id: String) {
        // Accept only a valid enabled model while the session is idle and alive.
        // Ignore model choices that are no longer enabled.
        guard !resourcesReleased, followUpRunID == nil,
              enabledExplanationModelOptions().contains(where: { $0.id == id }) else { return }
        followUpSelectedModelID = id
        followUpError = nil
        updateFollowUpComposer()
    }

    // followUpModelPage(): Reuse the launcher's model catalog without changing
    // the launcher's selected model.
    func followUpModelPage() -> PalettePage {
        PalettePage(rows: { [weak self] _ in
            // Return no palette rows after their owning session is released.
            guard let self else { return [] }
            let current = self.followUpModel().id
            var rows: [PaletteRow] = []
            var lastProvider: String?
            // Offer only models currently enabled in Settings.
            for option in enabledExplanationModelOptions() {
                let provider = modelProviderSectionName(textProvider(for: option.id).provider)
                // Insert one header when the list moves to another provider.
                if provider != lastProvider {
                    rows.append(.header(provider))
                    lastProvider = provider
                }
                rows.append(.item(PaletteItem(id: option.id, title: option.displayValue,
                    checked: option.id == current, action: { [weak self] in
                        self?.selectFollowUpModel(option.id)
                        return .close
                    })))
            }
            rows.append(.separator)
            rows.append(.item(PaletteItem(id: "all-models", title: localized("all_models", "All models"),
                chevron: true, action: { [weak self] in
                    // Close the action if no launcher remains to supply the full model page.
                    guard let launcher = self?.appDelegate?.launcherController else { return .close }
                    return .push(launcher.allModelsPage())
                })))
            return rows
        })
    }

    // showFollowUpModelPicker(anchor): Toggle the follow-up model palette while
    // keeping it anchored to the current composer.
    func showFollowUpModelPicker(anchor: NSView) {
        // Require a live idle session and a valid anchor window before showing model choices.
        guard !resourcesReleased, followUpRunID == nil, let window = anchor.window else { return }
        // A second invocation closes the already open model palette.
        if let panel = followUpModelPanel { panel.closePalette(); return }
        let panel = LauncherPalettePanel(anchorProvider: { [weak anchor] in
            // Avoid using a stale anchor after it leaves its window.
            guard let anchor, let window = anchor.window else { return .zero }
            return window.convertToScreen(anchor.convert(anchor.bounds, to: nil))
        }, width: 380)
        panel.onClose = { [weak self] in
            // Ignore palette dismissal after the result session is released.
            guard let self else { return }
            self.followUpModelPanel = nil
            // Do not refresh composer controls after session resources were released.
            guard !self.resourcesReleased else { return }
            self.updateFollowUpComposer()
            self.followUpComposer?.window?.makeFirstResponder(self.followUpComposer?.input)
        }
        panel.onCommandComma = { [weak self] in self?.appDelegate?.showPreferences(nil) }
        followUpModelPanel = panel
        panel.present(page: followUpModelPage(), over: window)
    }

    // installFollowUpComposer(root): Connect a follow-up composer to the
    // session's draft, model selection, and request actions.
    func installFollowUpComposer(in root: NSView) {
        let composer = ResultFollowUpComposer()
        composer.onChange = { [weak self] text in self?.followUpDraft = text }
        composer.onChooseModel = { [weak self] anchor in self?.showFollowUpModelPicker(anchor: anchor) }
        composer.onSubmit = { [weak self] in
            // Ignore composer submission after the owning result is released.
            guard let self else { return }
            // The composer button cancels an already running follow-up.
            if self.followUpRunID != nil { self.cancelFollowUp() }
            // An idle composer button starts a new follow-up request.
            else { self.submitFollowUp() }
        }
        root.addSubview(composer)
        followUpComposer = composer
        NSLayoutConstraint.activate([
            composer.leadingAnchor.constraint(equalTo: root.leadingAnchor),
            composer.trailingAnchor.constraint(equalTo: root.trailingAnchor),
            composer.bottomAnchor.constraint(equalTo: root.bottomAnchor)
        ])
        updateFollowUpComposer()
    }

    // updateFollowUpComposer(): Refresh the composer from the session's current
    // conversation state.
    func updateFollowUpComposer() {
        followUpComposer?.update(draft: followUpDraft, busy: followUpRunID != nil,
                                 model: followUpModel().name, error: followUpError)
    }

    // handleFollowUpLink(link, textView, index): Reject action links from model
    // text, even if they contain a valid message ID.
    func handleFollowUpLink(_ link: String, in textView: NSTextView, at index: Int) -> Bool {
        // Leave links outside the internal follow-up command scheme to other handlers.
        guard link.hasPrefix("langmin-followup-") else { return false }
        // Require a live session and a valid attributed command location before acting.
        guard !resourcesReleased, let storage = textView.textStorage,
              index >= 0, index < storage.length,
              storage.attribute(followUpActionAttribute, at: index, effectiveRange: nil) as? String == link else { return true }
        let actions = ["copy", "edit", "delete-reply", "delete-question"]
        // Match the link against the supported message actions.
        for action in actions {
            let prefix = "langmin-followup-\(action):"
            // Continue until the action prefix matches the clicked link.
            guard link.hasPrefix(prefix) else { continue }
            let id = String(link.dropFirst(prefix.count))
            // Copy actions export only the targeted completed reply.
            if action == "copy" {
                // Copy only when the targeted reply still exists and contains text.
                if let answer = config.conversation?.turns.first(where: { $0.id == id })?.answer, !answer.isEmpty {
                    copyToClipboard(markdownAttributedText(from: answer).string.replacingOccurrences(of: "\u{fffc}", with: ""))
                }
            } else if action == "edit" {
                // Edit actions open a draft for the targeted reply.
                beginTextEditing(replyID: id)
            } else {
                // Deletion actions remove the selected question or answer component.
                deleteFollowUpMessage(id: id, question: action == "delete-question")
            }
            return true
        }
        return true
    }

    // deleteFollowUpMessage(id, question): Save deletions before updating the
    // view. Cancel requests using the old history so they cannot restore it.
    func deleteFollowUpMessage(id: String, question: Bool) {
        // Require an existing conversation turn before deleting one of its messages.
        // Ignore deletion requests for a missing conversation turn.
        guard !resourcesReleased, var conversation = config.conversation,
              let index = conversation.turns.firstIndex(where: { $0.id == id }) else { return }
        // Delete only the user question when that is the chosen action.
        if question {
            // An already empty question requires no save or redraw.
            guard !conversation.turns[index].question.isEmpty else { return }
            conversation.turns[index].question = ""
        } else {
            // Delete only the assistant answer for an answer-deletion action.
            // An already empty answer requires no save or redraw.
            guard !conversation.turns[index].answer.isEmpty else { return }
            conversation.turns[index].answer = ""
        }
        conversation.turns.removeAll { $0.question.isEmpty && $0.answer.isEmpty }
        do {
            // Persist the changed conversation when the result belongs to the Library.
            if let savedLibraryID { try LibraryStore.setConversation(id: savedLibraryID, conversation: conversation) }
            let scroll = textView?.enclosingScrollView
            let position = scroll?.contentView.bounds.origin
            config.conversation = conversation
            followUpError = nil
            cancelFollowUp()
            // Preserve the reader's scroll position after redrawing the remaining messages.
            if let scroll, let position {
                scroll.contentView.scroll(to: position)
                scroll.reflectScrolledClipView(scroll.contentView)
            }
            // Refresh Library metadata after deleting a message from a saved conversation.
            if savedLibraryID != nil { appDelegate?.launcherController.libraryDidChange() }
        } catch {
            // Keep a readable deletion error in the composer when persistence fails.
            followUpError = String(format: localized("followup_delete_failed", "The message could not be deleted: %@"), error.localizedDescription)
            updateFollowUpComposer()
        }
    }

    // appendFollowUps(text, [includePending = true]): Append questions and
    // replies after the original result.
    func appendFollowUps(to text: NSMutableAttributedString, includePending: Bool = true) {
        // finishMessage([spacing = 0]): Use one paragraph break and a fixed gap
        // between messages, regardless of Markdown block spacing.
        func finishMessage(spacing: CGFloat = 0) {
            // An empty conversation has no preceding paragraph to finish.
            guard text.length > 0 else { return }
            let range = (text.string as NSString).paragraphRange(for: NSRange(location: text.length - 1, length: 1))
            let previous = text.attribute(.paragraphStyle, at: range.location, effectiveRange: nil) as? NSParagraphStyle
            let style = ((previous ?? viewerParagraphStyle()).mutableCopy() as? NSMutableParagraphStyle) ?? NSMutableParagraphStyle()
            style.paragraphSpacing = spacing
            text.addAttribute(.paragraphStyle, value: style, range: range)
            // Add a message boundary only when the existing text has no ending newline.
            if !text.string.hasSuffix("\n") {
                let font = text.attribute(.font, at: text.length - 1, effectiveRange: nil) as? NSFont ?? NSFont.systemFont(ofSize: config.fontSize)
                text.append(NSAttributedString(string: "\n", attributes: [.paragraphStyle: style, .font: font]))
            }
        }
        let labelStyle = (viewerParagraphStyle().mutableCopy() as? NSMutableParagraphStyle) ?? NSMutableParagraphStyle()
        labelStyle.lineSpacing = 0
        labelStyle.paragraphSpacingBefore = 20
        labelStyle.paragraphSpacing = 6
        // action(title, link): Create a tagged message-action link whose hover
        // appearance is managed separately.
        func action(_ title: String, link: String) -> NSAttributedString {
            NSAttributedString(string: title, attributes: [
                .font: NSFont.systemFont(ofSize: 11), .foregroundColor: NSColor.clear,
                .link: link, .toolTip: title, followUpActionAttribute: link
            ])
        }
        // question(value, deleteLink): Append a user-message header and body
        // with an optional delete action.
        func question(_ value: String, deleteLink: String?) {
            finishMessage()
            let start = text.length
            let header = NSMutableAttributedString(string: localized("followup_you", "You"), attributes: [
                .font: NSFont.systemFont(ofSize: 11, weight: .semibold), .foregroundColor: NSColor.controlAccentColor
            ])
            // Add a delete action to question headers that belong to saved conversation turns.
            if let deleteLink {
                header.append(NSAttributedString(string: "   ", attributes: [.font: NSFont.systemFont(ofSize: 11)]))
                header.append(action(localized("delete", "Delete"), link: deleteLink))
            }
            header.append(NSAttributedString(string: "\n", attributes: [.font: NSFont.systemFont(ofSize: 11)]))
            header.addAttribute(.paragraphStyle, value: labelStyle, range: NSRange(location: 0, length: header.length))
            text.append(header)
            text.append(NSAttributedString(string: value, attributes: viewerTextAttributes(
                size: config.fontSize, color: .labelColor, paragraphStyle: viewerParagraphStyle())))
            // Tag deletable question blocks so their hover controls can be located.
            if let deleteLink {
                text.addAttribute(followUpBlockAttribute, value: deleteLink, range: NSRange(location: start, length: text.length - start))
            }
        }
        // Render conversation turns in their saved order.
        for turn in config.conversation?.turns ?? [] {
            // Omit user-message blocks whose question was deleted.
            if !turn.question.isEmpty {
                question(turn.question, deleteLink: "langmin-followup-delete-question:\(turn.id)")
            }
            // Omit assistant-message blocks with no completed answer.
            guard !turn.answer.isEmpty else { continue }
            finishMessage()
            let start = text.length
            let header = NSMutableAttributedString(string: "Langmin · \(turn.modelName)   ", attributes: [
                .font: NSFont.systemFont(ofSize: 11), .foregroundColor: NSColor.secondaryLabelColor
            ])
            header.append(action(localized("followup_copy", "Copy reply"), link: "langmin-followup-copy:\(turn.id)"))
            header.append(NSAttributedString(string: "   ", attributes: [.font: NSFont.systemFont(ofSize: 11)]))
            header.append(action(localized("edit_text", "Edit Text"), link: "langmin-followup-edit:\(turn.id)"))
            header.append(NSAttributedString(string: "   ", attributes: [.font: NSFont.systemFont(ofSize: 11)]))
            header.append(action(localized("followup_delete_reply", "Delete reply"), link: "langmin-followup-delete-reply:\(turn.id)"))
            header.append(NSAttributedString(string: "\n", attributes: [.font: NSFont.systemFont(ofSize: 11)]))
            header.addAttribute(.paragraphStyle, value: labelStyle, range: NSRange(location: 0, length: header.length))
            text.append(header)
            text.append(markdownAttributedText(from: turn.answer))
            text.addAttribute(followUpBlockAttribute, value: "reply:\(turn.id)", range: NSRange(location: start, length: text.length - start))
        }
        if includePending, let pending = followUpPendingQuestion {
            // Show Delete only after the reply completes. The stop button cancels a pending request.
            question(pending, deleteLink: nil)
            // Place the waiting bubble just below the question.
            finishMessage(spacing: 6)
            let attachment = NSTextAttachment()
            attachment.attachmentCell = ResultFollowUpActivityCell()
            text.append(NSAttributedString(attachment: attachment))
        }
    }

    var exportedResultMarkdown: String {
        var result = content
        // Append retained conversation turns to exported Markdown.
        for turn in config.conversation?.turns ?? [] {
            var messages: [String] = []
            // Render user questions as quoted text in the export.
            if !turn.question.isEmpty {
                messages.append(turn.question.components(separatedBy: "\n").map { "> " + $0 }.joined(separator: "\n"))
            }
            // Include completed assistant answers in the export.
            if !turn.answer.isEmpty { messages.append(turn.answer) }
            // Add a separator only for a turn that still contains at least one message.
            if !messages.isEmpty { result += "\n\n---\n\n" + messages.joined(separator: "\n\n") }
        }
        return result
    }

    // refreshFollowUpText(): Rebuild the conversation display and reset diff
    // and narration decorations that no longer apply.
    func refreshFollowUpText() {
        // Do not rebuild text after the session has released its views.
        guard !resourcesReleased else { return }
        diffShown = false
        updateResultViewButtons()
        clearNarrationHighlight()
        applyResultText()
        applyNarrationCursorAttributes(for: narrationSegments)
        // Scroll a refreshed conversation to its newest displayed text when the view exists.
        if let textView {
            textView.scrollRangeToVisible(NSRange(location: (textView.string as NSString).length, length: 0))
        }
    }

    // submitFollowUp(): Check Pro access, sharing consent and secrets for the
    // full follow-up context. Recheck the destination after modal dialogs,
    // which may process Settings changes.
    func submitFollowUp() {
        // Start a follow-up only for a live session with no active request.
        guard !resourcesReleased, followUpRunID == nil else { return }
        let question = followUpDraft.trimmingCharacters(in: .whitespacesAndNewlines)
        // Ignore drafts containing only whitespace.
        guard !question.isEmpty else { return }
        let model = followUpModel()
        let conversation = config.conversation ?? ResultConversation(originalRequest: "", modelID: model.id)
        let preferences = loadAppPreferences()
        let research = preferences.webResearchEnabled && modelSupportsWebResearch(model.id)
        let runID = UUID()
        followUpRunID = runID
        followUpRequestModel = model
        followUpModelPanel?.closePalette()
        followUpError = nil
        // Prepare the bounded conversation prompt before starting the follow-up request.
        do {
            let prepared = try resultFollowUpPrompt(question: question, originalResult: content,
                conversation: conversation, mode: config.mode, research: research,
                contextLimit: textProvider(for: model.id).provider == .apple ? 6_000 : 32_000)
            let destination = remoteTextDestination(for: model.id)
            updateFollowUpComposer()
            // Require sharing permission before sending the full prepared conversation context.
            guard confirmRemoteTextSharingIfNeeded(input: prepared.secretScanText, model: model.id) else {
                // Cancel only the request that is still current after consent was declined.
                if followUpRunID == runID { cancelFollowUp() }
                return
            }
            // Stop if the session or request changed while a modal consent prompt was open.
            guard !resourcesReleased, followUpRunID == runID else { return }
            // Require a fresh submission if the endpoint changed after sharing permission was checked.
            guard remoteTextDestination(for: model.id)?.consentID == destination?.consentID else {
                throw HelperFailure(message: "The model endpoint changed. Send the follow-up again to use the new endpoint.")
            }
            followUpPendingQuestion = question
            refreshFollowUpText()
            let prompt = ExplanationPrompt(instructions: applyLanguageLevel(to: prepared.instructions, level: config.languageLevel),
                                           input: prepared.input, conversationMessages: prepared.messages)
            let task = try startTextRequest(model: model.id, prompt: prompt, emptyMessage: "The model returned an empty reply.", research: research) { [weak self] result in
                DispatchQueue.main.async {
                    // Ignore response callbacks from cancelled, superseded, or released sessions.
                    guard let self, !self.resourcesReleased, self.followUpRunID == runID else { return }
                    self.followUpRunID = nil
                    self.followUpRequestModel = nil
                    self.followUpTask = nil
                    self.followUpPendingQuestion = nil
                    // Validate the received answer before adding it to conversation history.
                    do {
                        // Clean generated replies before saving or reusing them as context.
                        let answer = watermarkCleanedGeneratedText(try result.get())
                            .trimmingCharacters(in: .whitespacesAndNewlines)
                        // Report an empty answer instead of saving an apparently completed reply.
                        guard !answer.isEmpty else { throw HelperFailure(message: "The model returned an empty reply.") }
                        var updated = conversation
                        updated.modelID = model.id
                        updated.turns.append(ResultFollowUpTurn(question: question, answer: answer, modelID: model.id, modelName: model.name))
                        self.config.conversation = updated
                        self.followUpDraft = ""
                        // Update the saved conversation without changing the original result or its
                        // assets.
                        if let id = self.savedLibraryID {
                            // Try persisting the new reply while keeping the received answer available on failure.
                            do {
                                try LibraryStore.setConversation(id: id, conversation: updated)
                                self.appDelegate?.launcherController.libraryDidChange()
                            } catch {
                                // Retain a received reply with an explicit notice when saving the conversation fails.
                                self.followUpError = "Reply received, but the conversation could not be saved: \(error.localizedDescription)"
                            }
                        }
                    } catch {
                        // Keep the draft on failure; add an exchange only after a successful reply.
                        self.followUpError = error.localizedDescription
                    }
                    self.updateFollowUpComposer()
                    self.refreshFollowUpText()
                }
            }
            // Cancel a newly constructed task if the session or request changed before it could start.
            guard !resourcesReleased, followUpRunID == runID else { task.cancel(); return }
            followUpTask = task
            task.resume()
        } catch {
            // Report request-setup failures only while they still belong to this session's active run.
            // Ignore setup errors from requests that have already been superseded.
            guard !resourcesReleased, followUpRunID == runID else { return }
            followUpRunID = nil
            followUpRequestModel = nil
            followUpTask = nil
            followUpPendingQuestion = nil
            followUpError = error.localizedDescription
            updateFollowUpComposer()
            refreshFollowUpText()
        }
    }

    // cancelFollowUp(): Invalidate the follow-up token before cancelling its
    // task so late callbacks cannot update the result.
    func cancelFollowUp() {
        followUpRunID = nil
        followUpRequestModel = nil
        followUpTask?.cancel()
        followUpTask = nil
        followUpPendingQuestion = nil
        // Refresh cancellation state only while the result's views are still available.
        if !resourcesReleased {
            updateFollowUpComposer()
            refreshFollowUpText()
        }
    }
}
